import type { Metadata } from 'next'
import { Inter,Syncopate } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
const syncopate = Syncopate({weight:'400',subsets:['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className +" bg-zinc-800"}>{children}</body>
    </html>
  )
}
